// <auto-generated />
using System;
using CollegeSystemSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CollegeSystemSystem.Migrations
{
    [DbContext(typeof(CollegeSystemDbContext))]
    [Migration("20211122070308_Seeding")]
    partial class Seeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CollegeSystemSystem.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Course");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseName = "Administration"
                        },
                        new
                        {
                            Id = 2,
                            CourseName = "Mechanical Engineer"
                        },
                        new
                        {
                            Id = 3,
                            CourseName = "Finance"
                        },
                        new
                        {
                            Id = 4,
                            CourseName = "Technology"
                        });
                });

            modelBuilder.Entity("CollegeSystemSystem.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double?>("GradeNumber")
                        .HasColumnType("float");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Grade");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GradeNumber = 1.0,
                            StudentId = 1,
                            SubjectId = 10
                        },
                        new
                        {
                            Id = 2,
                            GradeNumber = 6.0,
                            StudentId = 1,
                            SubjectId = 11
                        },
                        new
                        {
                            Id = 3,
                            GradeNumber = 9.0,
                            StudentId = 1,
                            SubjectId = 12
                        },
                        new
                        {
                            Id = 4,
                            GradeNumber = 5.0,
                            StudentId = 2,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 5,
                            GradeNumber = 3.0,
                            StudentId = 2,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 6,
                            GradeNumber = 0.0,
                            StudentId = 2,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 7,
                            GradeNumber = 9.0,
                            StudentId = 3,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 8,
                            GradeNumber = 10.0,
                            StudentId = 3,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 9,
                            GradeNumber = 8.0,
                            StudentId = 3,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 10,
                            GradeNumber = 7.0,
                            StudentId = 4,
                            SubjectId = 7
                        },
                        new
                        {
                            Id = 11,
                            GradeNumber = 3.0,
                            StudentId = 4,
                            SubjectId = 8
                        },
                        new
                        {
                            Id = 12,
                            GradeNumber = 6.0,
                            StudentId = 4,
                            SubjectId = 9
                        },
                        new
                        {
                            Id = 13,
                            GradeNumber = 1.0,
                            StudentId = 5,
                            SubjectId = 7
                        },
                        new
                        {
                            Id = 14,
                            GradeNumber = 2.0,
                            StudentId = 5,
                            SubjectId = 8
                        },
                        new
                        {
                            Id = 15,
                            GradeNumber = 1.0,
                            StudentId = 5,
                            SubjectId = 9
                        },
                        new
                        {
                            Id = 16,
                            GradeNumber = 4.0,
                            StudentId = 6,
                            SubjectId = 10
                        },
                        new
                        {
                            Id = 17,
                            GradeNumber = 10.0,
                            StudentId = 6,
                            SubjectId = 11
                        },
                        new
                        {
                            Id = 18,
                            GradeNumber = 8.0,
                            StudentId = 6,
                            SubjectId = 12
                        },
                        new
                        {
                            Id = 19,
                            GradeNumber = 2.0,
                            StudentId = 7,
                            SubjectId = 7
                        },
                        new
                        {
                            Id = 20,
                            GradeNumber = 1.0,
                            StudentId = 7,
                            SubjectId = 8
                        },
                        new
                        {
                            Id = 21,
                            GradeNumber = 4.0,
                            StudentId = 7,
                            SubjectId = 9
                        },
                        new
                        {
                            Id = 22,
                            GradeNumber = 4.0,
                            StudentId = 8,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 23,
                            GradeNumber = 6.0,
                            StudentId = 8,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 24,
                            GradeNumber = 0.0,
                            StudentId = 8,
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 25,
                            GradeNumber = 8.0,
                            StudentId = 9,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 26,
                            GradeNumber = 2.0,
                            StudentId = 9,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 27,
                            GradeNumber = 0.0,
                            StudentId = 9,
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 28,
                            GradeNumber = 9.0,
                            StudentId = 10,
                            SubjectId = 10
                        },
                        new
                        {
                            Id = 29,
                            GradeNumber = 5.0,
                            StudentId = 10,
                            SubjectId = 11
                        },
                        new
                        {
                            Id = 30,
                            GradeNumber = 9.0,
                            StudentId = 10,
                            SubjectId = 12
                        },
                        new
                        {
                            Id = 31,
                            GradeNumber = 0.0,
                            StudentId = 11,
                            SubjectId = 10
                        },
                        new
                        {
                            Id = 32,
                            GradeNumber = 8.0,
                            StudentId = 11,
                            SubjectId = 11
                        },
                        new
                        {
                            Id = 33,
                            GradeNumber = 1.0,
                            StudentId = 11,
                            SubjectId = 12
                        },
                        new
                        {
                            Id = 34,
                            GradeNumber = 4.0,
                            StudentId = 12,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 35,
                            GradeNumber = 9.0,
                            StudentId = 12,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 36,
                            GradeNumber = 0.0,
                            StudentId = 12,
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 37,
                            GradeNumber = 3.0,
                            StudentId = 13,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 38,
                            GradeNumber = 7.0,
                            StudentId = 13,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 39,
                            GradeNumber = 5.0,
                            StudentId = 13,
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 40,
                            GradeNumber = 5.0,
                            StudentId = 14,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 41,
                            GradeNumber = 7.0,
                            StudentId = 14,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 42,
                            GradeNumber = 4.0,
                            StudentId = 14,
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 43,
                            GradeNumber = 5.0,
                            StudentId = 15,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 44,
                            GradeNumber = 1.0,
                            StudentId = 15,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 45,
                            GradeNumber = 0.0,
                            StudentId = 15,
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 46,
                            GradeNumber = 4.0,
                            StudentId = 16,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 47,
                            GradeNumber = 1.0,
                            StudentId = 16,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 48,
                            GradeNumber = 3.0,
                            StudentId = 16,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 49,
                            GradeNumber = 10.0,
                            StudentId = 17,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 50,
                            GradeNumber = 9.0,
                            StudentId = 17,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 51,
                            GradeNumber = 2.0,
                            StudentId = 17,
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 52,
                            GradeNumber = 5.0,
                            StudentId = 18,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 53,
                            GradeNumber = 10.0,
                            StudentId = 18,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 54,
                            GradeNumber = 2.0,
                            StudentId = 18,
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 55,
                            GradeNumber = 9.0,
                            StudentId = 19,
                            SubjectId = 10
                        },
                        new
                        {
                            Id = 56,
                            GradeNumber = 10.0,
                            StudentId = 19,
                            SubjectId = 11
                        },
                        new
                        {
                            Id = 57,
                            GradeNumber = 10.0,
                            StudentId = 19,
                            SubjectId = 12
                        },
                        new
                        {
                            Id = 58,
                            GradeNumber = 2.0,
                            StudentId = 20,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 59,
                            GradeNumber = 1.0,
                            StudentId = 20,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 60,
                            GradeNumber = 6.0,
                            StudentId = 20,
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 61,
                            GradeNumber = 10.0,
                            StudentId = 21,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 62,
                            GradeNumber = 4.0,
                            StudentId = 21,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 63,
                            GradeNumber = 1.0,
                            StudentId = 21,
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 64,
                            GradeNumber = 6.0,
                            StudentId = 22,
                            SubjectId = 7
                        },
                        new
                        {
                            Id = 65,
                            GradeNumber = 9.0,
                            StudentId = 22,
                            SubjectId = 8
                        },
                        new
                        {
                            Id = 66,
                            GradeNumber = 0.0,
                            StudentId = 22,
                            SubjectId = 9
                        },
                        new
                        {
                            Id = 67,
                            GradeNumber = 8.0,
                            StudentId = 23,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 68,
                            GradeNumber = 6.0,
                            StudentId = 23,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 69,
                            GradeNumber = 1.0,
                            StudentId = 23,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 70,
                            GradeNumber = 5.0,
                            StudentId = 24,
                            SubjectId = 10
                        },
                        new
                        {
                            Id = 71,
                            GradeNumber = 0.0,
                            StudentId = 24,
                            SubjectId = 11
                        },
                        new
                        {
                            Id = 72,
                            GradeNumber = 1.0,
                            StudentId = 24,
                            SubjectId = 12
                        },
                        new
                        {
                            Id = 73,
                            GradeNumber = 3.0,
                            StudentId = 25,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 74,
                            GradeNumber = 6.0,
                            StudentId = 25,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 75,
                            GradeNumber = 2.0,
                            StudentId = 25,
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 76,
                            GradeNumber = 5.0,
                            StudentId = 26,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 77,
                            GradeNumber = 10.0,
                            StudentId = 26,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 78,
                            GradeNumber = 5.0,
                            StudentId = 26,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 79,
                            GradeNumber = 1.0,
                            StudentId = 27,
                            SubjectId = 10
                        },
                        new
                        {
                            Id = 80,
                            GradeNumber = 2.0,
                            StudentId = 27,
                            SubjectId = 11
                        },
                        new
                        {
                            Id = 81,
                            GradeNumber = 3.0,
                            StudentId = 27,
                            SubjectId = 12
                        },
                        new
                        {
                            Id = 82,
                            GradeNumber = 4.0,
                            StudentId = 28,
                            SubjectId = 10
                        },
                        new
                        {
                            Id = 83,
                            GradeNumber = 10.0,
                            StudentId = 28,
                            SubjectId = 11
                        },
                        new
                        {
                            Id = 84,
                            GradeNumber = 0.0,
                            StudentId = 28,
                            SubjectId = 12
                        },
                        new
                        {
                            Id = 85,
                            GradeNumber = 2.0,
                            StudentId = 29,
                            SubjectId = 10
                        },
                        new
                        {
                            Id = 86,
                            GradeNumber = 6.0,
                            StudentId = 29,
                            SubjectId = 11
                        },
                        new
                        {
                            Id = 87,
                            GradeNumber = 0.0,
                            StudentId = 29,
                            SubjectId = 12
                        },
                        new
                        {
                            Id = 88,
                            GradeNumber = 8.0,
                            StudentId = 30,
                            SubjectId = 10
                        },
                        new
                        {
                            Id = 89,
                            GradeNumber = 9.0,
                            StudentId = 30,
                            SubjectId = 11
                        },
                        new
                        {
                            Id = 90,
                            GradeNumber = 5.0,
                            StudentId = 30,
                            SubjectId = 12
                        },
                        new
                        {
                            Id = 91,
                            GradeNumber = 1.0,
                            StudentId = 31,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 92,
                            GradeNumber = 8.0,
                            StudentId = 31,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 93,
                            GradeNumber = 5.0,
                            StudentId = 31,
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 94,
                            GradeNumber = 7.0,
                            StudentId = 32,
                            SubjectId = 10
                        },
                        new
                        {
                            Id = 95,
                            GradeNumber = 2.0,
                            StudentId = 32,
                            SubjectId = 11
                        },
                        new
                        {
                            Id = 96,
                            GradeNumber = 1.0,
                            StudentId = 32,
                            SubjectId = 12
                        },
                        new
                        {
                            Id = 97,
                            GradeNumber = 10.0,
                            StudentId = 33,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 98,
                            GradeNumber = 9.0,
                            StudentId = 33,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 99,
                            GradeNumber = 8.0,
                            StudentId = 33,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 100,
                            GradeNumber = 0.0,
                            StudentId = 34,
                            SubjectId = 10
                        },
                        new
                        {
                            Id = 101,
                            GradeNumber = 6.0,
                            StudentId = 34,
                            SubjectId = 11
                        },
                        new
                        {
                            Id = 102,
                            GradeNumber = 4.0,
                            StudentId = 34,
                            SubjectId = 12
                        },
                        new
                        {
                            Id = 103,
                            GradeNumber = 0.0,
                            StudentId = 35,
                            SubjectId = 10
                        },
                        new
                        {
                            Id = 104,
                            GradeNumber = 0.0,
                            StudentId = 35,
                            SubjectId = 11
                        },
                        new
                        {
                            Id = 105,
                            GradeNumber = 2.0,
                            StudentId = 35,
                            SubjectId = 12
                        },
                        new
                        {
                            Id = 106,
                            GradeNumber = 4.0,
                            StudentId = 36,
                            SubjectId = 10
                        },
                        new
                        {
                            Id = 107,
                            GradeNumber = 2.0,
                            StudentId = 36,
                            SubjectId = 11
                        },
                        new
                        {
                            Id = 108,
                            GradeNumber = 6.0,
                            StudentId = 36,
                            SubjectId = 12
                        },
                        new
                        {
                            Id = 109,
                            GradeNumber = 8.0,
                            StudentId = 37,
                            SubjectId = 7
                        },
                        new
                        {
                            Id = 110,
                            GradeNumber = 3.0,
                            StudentId = 37,
                            SubjectId = 8
                        },
                        new
                        {
                            Id = 111,
                            GradeNumber = 3.0,
                            StudentId = 37,
                            SubjectId = 9
                        },
                        new
                        {
                            Id = 112,
                            GradeNumber = 5.0,
                            StudentId = 38,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 113,
                            GradeNumber = 6.0,
                            StudentId = 38,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 114,
                            GradeNumber = 8.0,
                            StudentId = 38,
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 115,
                            GradeNumber = 0.0,
                            StudentId = 39,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 116,
                            GradeNumber = 1.0,
                            StudentId = 39,
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 117,
                            GradeNumber = 6.0,
                            StudentId = 39,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 118,
                            GradeNumber = 5.0,
                            StudentId = 40,
                            SubjectId = 10
                        },
                        new
                        {
                            Id = 119,
                            GradeNumber = 10.0,
                            StudentId = 40,
                            SubjectId = 11
                        },
                        new
                        {
                            Id = 120,
                            GradeNumber = 8.0,
                            StudentId = 40,
                            SubjectId = 12
                        },
                        new
                        {
                            Id = 121,
                            GradeNumber = 5.0,
                            StudentId = 41,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 122,
                            GradeNumber = 9.0,
                            StudentId = 41,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 123,
                            GradeNumber = 1.0,
                            StudentId = 41,
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 124,
                            GradeNumber = 8.0,
                            StudentId = 42,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 125,
                            GradeNumber = 6.0,
                            StudentId = 42,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 126,
                            GradeNumber = 3.0,
                            StudentId = 42,
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 127,
                            GradeNumber = 7.0,
                            StudentId = 43,
                            SubjectId = 10
                        },
                        new
                        {
                            Id = 128,
                            GradeNumber = 10.0,
                            StudentId = 43,
                            SubjectId = 11
                        },
                        new
                        {
                            Id = 129,
                            GradeNumber = 0.0,
                            StudentId = 43,
                            SubjectId = 12
                        },
                        new
                        {
                            Id = 130,
                            GradeNumber = 6.0,
                            StudentId = 44,
                            SubjectId = 10
                        },
                        new
                        {
                            Id = 131,
                            GradeNumber = 1.0,
                            StudentId = 44,
                            SubjectId = 11
                        },
                        new
                        {
                            Id = 132,
                            GradeNumber = 8.0,
                            StudentId = 44,
                            SubjectId = 12
                        },
                        new
                        {
                            Id = 133,
                            GradeNumber = 8.0,
                            StudentId = 45,
                            SubjectId = 4
                        },
                        new
                        {
                            Id = 134,
                            GradeNumber = 1.0,
                            StudentId = 45,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 135,
                            GradeNumber = 3.0,
                            StudentId = 45,
                            SubjectId = 6
                        },
                        new
                        {
                            Id = 136,
                            GradeNumber = 0.0,
                            StudentId = 46,
                            SubjectId = 10
                        },
                        new
                        {
                            Id = 137,
                            GradeNumber = 6.0,
                            StudentId = 46,
                            SubjectId = 11
                        },
                        new
                        {
                            Id = 138,
                            GradeNumber = 5.0,
                            StudentId = 46,
                            SubjectId = 12
                        },
                        new
                        {
                            Id = 139,
                            GradeNumber = 7.0,
                            StudentId = 47,
                            SubjectId = 7
                        },
                        new
                        {
                            Id = 140,
                            GradeNumber = 4.0,
                            StudentId = 47,
                            SubjectId = 8
                        },
                        new
                        {
                            Id = 141,
                            GradeNumber = 10.0,
                            StudentId = 47,
                            SubjectId = 9
                        },
                        new
                        {
                            Id = 142,
                            GradeNumber = 3.0,
                            StudentId = 48,
                            SubjectId = 10
                        },
                        new
                        {
                            Id = 143,
                            GradeNumber = 2.0,
                            StudentId = 48,
                            SubjectId = 11
                        },
                        new
                        {
                            Id = 144,
                            GradeNumber = 7.0,
                            StudentId = 48,
                            SubjectId = 12
                        },
                        new
                        {
                            Id = 145,
                            GradeNumber = 9.0,
                            StudentId = 49,
                            SubjectId = 7
                        },
                        new
                        {
                            Id = 146,
                            GradeNumber = 10.0,
                            StudentId = 49,
                            SubjectId = 8
                        },
                        new
                        {
                            Id = 147,
                            GradeNumber = 6.0,
                            StudentId = 49,
                            SubjectId = 9
                        },
                        new
                        {
                            Id = 148,
                            GradeNumber = 10.0,
                            StudentId = 50,
                            SubjectId = 10
                        },
                        new
                        {
                            Id = 149,
                            GradeNumber = 9.0,
                            StudentId = 50,
                            SubjectId = 11
                        },
                        new
                        {
                            Id = 150,
                            GradeNumber = 5.0,
                            StudentId = 50,
                            SubjectId = 12
                        });
                });

            modelBuilder.Entity("CollegeSystemSystem.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2001, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 4,
                            Name = "Rolf Ellsworth"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1970, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 1,
                            Name = "Dominique Bunker"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1956, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 1,
                            Name = "Glenda Connealy"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(2003, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 3,
                            Name = "Pamela Volkert"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1964, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 3,
                            Name = "Michael Goodyear"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1957, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 4,
                            Name = "Mark Latshaw"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1957, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 3,
                            Name = "Ella Watson"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1957, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 2,
                            Name = "Gracie Johnson"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(2003, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 2,
                            Name = "Monty Brace"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(1956, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 4,
                            Name = "Ronald Robinson"
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateTime(1991, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 4,
                            Name = "Matthew Ruscio"
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = new DateTime(1995, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 2,
                            Name = "Linda Grove"
                        },
                        new
                        {
                            Id = 13,
                            BirthDate = new DateTime(1984, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 2,
                            Name = "Jaimee Barnhart"
                        },
                        new
                        {
                            Id = 14,
                            BirthDate = new DateTime(2002, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 2,
                            Name = "Michell Crout"
                        },
                        new
                        {
                            Id = 15,
                            BirthDate = new DateTime(1986, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 2,
                            Name = "Linda Rowe"
                        },
                        new
                        {
                            Id = 16,
                            BirthDate = new DateTime(1983, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 1,
                            Name = "Thomas Dolan"
                        },
                        new
                        {
                            Id = 17,
                            BirthDate = new DateTime(1993, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 2,
                            Name = "Johanna Sobina"
                        },
                        new
                        {
                            Id = 18,
                            BirthDate = new DateTime(1956, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 2,
                            Name = "Hazel Obrien"
                        },
                        new
                        {
                            Id = 19,
                            BirthDate = new DateTime(1976, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 4,
                            Name = "Elicia Weaver"
                        },
                        new
                        {
                            Id = 20,
                            BirthDate = new DateTime(1969, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 2,
                            Name = "David Munoz"
                        },
                        new
                        {
                            Id = 21,
                            BirthDate = new DateTime(1991, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 2,
                            Name = "Tara Ebner"
                        },
                        new
                        {
                            Id = 22,
                            BirthDate = new DateTime(1969, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 3,
                            Name = "Lana Lofty"
                        },
                        new
                        {
                            Id = 23,
                            BirthDate = new DateTime(1977, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 1,
                            Name = "Anna Johnson"
                        },
                        new
                        {
                            Id = 24,
                            BirthDate = new DateTime(1974, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 4,
                            Name = "Pamela Mitchell"
                        },
                        new
                        {
                            Id = 25,
                            BirthDate = new DateTime(1993, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 2,
                            Name = "Katrina Curtis"
                        },
                        new
                        {
                            Id = 26,
                            BirthDate = new DateTime(1971, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 1,
                            Name = "Theodore Fitts"
                        },
                        new
                        {
                            Id = 27,
                            BirthDate = new DateTime(1977, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 4,
                            Name = "Kristen Cantu"
                        },
                        new
                        {
                            Id = 28,
                            BirthDate = new DateTime(2002, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 4,
                            Name = "Matthew Welch"
                        },
                        new
                        {
                            Id = 29,
                            BirthDate = new DateTime(1988, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 4,
                            Name = "Tiffany Phelps"
                        },
                        new
                        {
                            Id = 30,
                            BirthDate = new DateTime(1971, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 4,
                            Name = "Gloria Hernandez"
                        },
                        new
                        {
                            Id = 31,
                            BirthDate = new DateTime(1979, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 2,
                            Name = "Paul Dixon"
                        },
                        new
                        {
                            Id = 32,
                            BirthDate = new DateTime(1991, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 4,
                            Name = "Jose Jiggetts"
                        },
                        new
                        {
                            Id = 33,
                            BirthDate = new DateTime(1983, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 1,
                            Name = "John Conner"
                        },
                        new
                        {
                            Id = 34,
                            BirthDate = new DateTime(1966, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 4,
                            Name = "Nolan Mixon"
                        },
                        new
                        {
                            Id = 35,
                            BirthDate = new DateTime(1953, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 4,
                            Name = "Gregg Otto"
                        },
                        new
                        {
                            Id = 36,
                            BirthDate = new DateTime(1973, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 4,
                            Name = "Anne Mceachern"
                        },
                        new
                        {
                            Id = 37,
                            BirthDate = new DateTime(1995, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 3,
                            Name = "Jeffrey Steiner"
                        },
                        new
                        {
                            Id = 38,
                            BirthDate = new DateTime(1997, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 2,
                            Name = "Alice Poulin"
                        },
                        new
                        {
                            Id = 39,
                            BirthDate = new DateTime(1969, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 1,
                            Name = "Kellie Luttrell"
                        },
                        new
                        {
                            Id = 40,
                            BirthDate = new DateTime(1992, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 4,
                            Name = "Ethel Riseden"
                        },
                        new
                        {
                            Id = 41,
                            BirthDate = new DateTime(1966, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 2,
                            Name = "Lily Kiser"
                        },
                        new
                        {
                            Id = 42,
                            BirthDate = new DateTime(1950, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 2,
                            Name = "Cynthia Berry"
                        },
                        new
                        {
                            Id = 43,
                            BirthDate = new DateTime(1988, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 4,
                            Name = "Irene Gardner"
                        },
                        new
                        {
                            Id = 44,
                            BirthDate = new DateTime(1979, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 4,
                            Name = "Fred Caison"
                        },
                        new
                        {
                            Id = 45,
                            BirthDate = new DateTime(1977, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 2,
                            Name = "Daniel Chin"
                        },
                        new
                        {
                            Id = 46,
                            BirthDate = new DateTime(2000, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 4,
                            Name = "Rubye Debord"
                        },
                        new
                        {
                            Id = 47,
                            BirthDate = new DateTime(1955, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 3,
                            Name = "Raymond Becerra"
                        },
                        new
                        {
                            Id = 48,
                            BirthDate = new DateTime(1992, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 4,
                            Name = "Susan Campos"
                        },
                        new
                        {
                            Id = 49,
                            BirthDate = new DateTime(1951, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 3,
                            Name = "Kathy Smith"
                        },
                        new
                        {
                            Id = 50,
                            BirthDate = new DateTime(1969, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CourseId = 4,
                            Name = "Marylyn Reine"
                        });
                });

            modelBuilder.Entity("CollegeSystemSystem.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Subject");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            SubjectName = "Project Management",
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            SubjectName = "Negotiation",
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 1,
                            SubjectName = "International Relashionship",
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 2,
                            SubjectName = "Physics",
                            TeacherId = 4
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 2,
                            SubjectName = "Vibrations",
                            TeacherId = 5
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 2,
                            SubjectName = "Rigid Body Mechanics",
                            TeacherId = 6
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 3,
                            SubjectName = "Taxes",
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 3,
                            SubjectName = "Mutual Funds",
                            TeacherId = 5
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 3,
                            SubjectName = "Basic Finances",
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 4,
                            SubjectName = "Database Design",
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 11,
                            CourseId = 4,
                            SubjectName = "Functional Code",
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 12,
                            CourseId = 4,
                            SubjectName = "JavaScript Code",
                            TeacherId = 6
                        });
                });

            modelBuilder.Entity("CollegeSystemSystem.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<double>("Wage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Teacher");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1997, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rodrigo Marques",
                            Wage = 3000.0
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1984, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Beatriz Almeida",
                            Wage = 6000.0
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1990, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tomás Gonçalves",
                            Wage = 4000.0
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1989, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Francisco Correia",
                            Wage = 3340.0
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(2001, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Catarina Carvalho",
                            Wage = 5010.0
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(2004, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mariana Ferreira",
                            Wage = 6800.0
                        });
                });

            modelBuilder.Entity("CollegeSystemSystem.Models.Grade", b =>
                {
                    b.HasOne("CollegeSystemSystem.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("CollegeSystemSystem.Models.Subject", "Subject")
                        .WithMany("Grades")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("CollegeSystemSystem.Models.Student", b =>
                {
                    b.HasOne("CollegeSystemSystem.Models.Course", "Course")
                        .WithMany("Students")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CollegeSystemSystem.Models.Subject", b =>
                {
                    b.HasOne("CollegeSystemSystem.Models.Course", "Course")
                        .WithMany("Subjects")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("CollegeSystemSystem.Models.Teacher", "Teacher")
                        .WithMany("Subjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("CollegeSystemSystem.Models.Course", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("CollegeSystemSystem.Models.Student", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("CollegeSystemSystem.Models.Subject", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("CollegeSystemSystem.Models.Teacher", b =>
                {
                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
